name: continuous-integration

on:
  pull_request:
    branches: [ main ]

jobs:
  run-actions:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout base
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: checkout head
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node env
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true